# Generated by Django 2.0.2 on 2018-03-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listavj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_portada'),
        ),
    ]
