# Generated by Django 2.0.2 on 2018-03-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listavj', '0002_videojuego_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='desarrollador',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_portada'),
        ),
        migrations.AddField(
            model_name='distribuidor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_portada'),
        ),
        migrations.AddField(
            model_name='genero',
            name='descripcion',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
