# Generated by Django 2.0.2 on 2018-03-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listavj', '0003_auto_20180309_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='plataforma',
        ),
    ]
