# Generated by Django 2.0.2 on 2018-03-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listavj', '0004_remove_videojuego_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='plataforma',
            field=models.ManyToManyField(blank=True, null=True, to='listavj.Plataforma'),
        ),
    ]
